server:
  port: 8880
  mode: release #debug or release
  baseurl:
jwt:
  expire: 1 # hour
  keyfile:
  password:
log:
  level: debug
bitmarksdk:
  token:
  network: testnet
orm:
  conn: user=autonomy password= host= port= dbname=autonomy connect_timeout=10 pool_max_conns=10
mongo:
  conn: mongodb://user:password@localhost:27017
  database: test
  connect_timeout: 10
  pool: 10
sentry:
  dsn:
  dist: 0.1
  environment: testnet
account:
  seed:
onesignal:
  endpoint: https://onesignal.com
  key:
  appid:
clients:
  android:
    minimum_client_version: 1
  ios:
    minimum_client_version: 1
